# Generated by Django 5.1.7 on 2025-03-24 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('social_security_number', models.CharField(max_length=255, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='customer_pictures')),
                ('business_field', models.CharField(blank=True, max_length=255, null=True)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='MainManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('access_code', models.CharField(max_length=255, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('grand_balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=255, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='manager_pictures')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('management_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('drive_license_id', models.CharField(max_length=255, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='driver_pictures')),
                ('debt_balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('travel_count', models.IntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('assigned_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='Users.manager')),
            ],
        ),
    ]
