# Generated by Django 5.1.7 on 2025-03-24 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Storage', '__first__'),
        ('Transportation', '__first__'),
        ('Users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('storage_period', models.IntegerField()),
                ('transport_distance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transport_range', models.CharField(choices=[('International', 'International'), ('Interior', 'Interior'), ('Intrastate', 'Intrastate')], max_length=50)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transportation.transportcar')),
                ('cargo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Storage.cargo')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.driver')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('cryptocurrency', 'Cryptocurrency')], max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Financial.order')),
            ],
        ),
    ]
